
[common]

	[common.attackRange]
		attack_range_potion_enabled = true
		attack_range_multiplier = 1.25

	[common.shield]
		bone_durability_multiplier = 2.0
		obsidian_durability_multiplier = 5.0
		netherite_durability_multiplier = 20.0
		leather_durability_multiplier = 1.5

	[common.potion]
		freeze_2_duration = 50
		freeze_1_duration = 15

	[common.reachDistance]
		reach_distance_potion_enabled = true
		reach_distance_multiplier = 1.5

[client]
	night_vision_key = true

